### ISSUE TITLE
edit peers

### ISSUE THREAD

**Issue by jorisbontje** [BlockchainSociety/TrustDavis#19]
change:
- max liability
- premium

**Comment by 0xc1c4da** [comment]
kind of done, but autoforms type="method-update"  generates a mongo $set query, which i'm unsure how to check() against.

**Comment by jorisbontje** [comment]
```
I20150429-08:55:57.264(2)? modifyPeerMaxLiabilityAndPremium { '$set': { premiumPct: 0, maxLiability: 15 } } { isSimulation: false,
I20150429-08:55:57.265(2)?   _unblock: [Function],
I20150429-08:55:57.265(2)?   _calledUnblock: false,
I20150429-08:55:57.265(2)?   userId: 'cNP27poLaPutfPq6G',
I20150429-08:55:57.265(2)?   _setUserId: [Function],
I20150429-08:55:57.265(2)?   connection:
I20150429-08:55:57.266(2)?    { id: 'sosA2K2aq3h7jY4kN',
I20150429-08:55:57.266(2)?      close: [Function],
I20150429-08:55:57.266(2)?      onClose: [Function],
I20150429-08:55:57.266(2)?      clientAddress: '127.0.0.1',
I20150429-08:55:57.266(2)?      httpHeaders:
I20150429-08:55:57.266(2)?       { 'x-forwarded-for': '127.0.0.1',
I20150429-08:55:57.266(2)?         host: 'localhost:3000',
I20150429-08:55:57.266(2)?         'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36',
I20150429-08:55:57.266(2)?         'accept-language': 'en-US,en;q=0.8,nl;q=0.6' } },
I20150429-08:55:57.267(2)?   randomSeed: null,
I20150429-08:55:57.267(2)?   randomStream: null }
I20150429-08:55:57.267(2)? Exception while invoking method 'modifyPeerMaxLiabilityAndPremium' Error: Did not check() all arguments during call to 'modifyPeerMaxLiabilityAndPremium'
I20150429-08:55:57.267(2)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150429-08:55:57.267(2)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150429-08:55:57.267(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150429-08:55:57.267(2)?     at packages/ddp/livedata_server.js:648:1
I20150429-08:55:57.267(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150429-08:55:57.267(2)?     at packages/ddp/livedata_server.js:647:1
I20150429-08:55:57.268(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150429-08:55:57.268(2)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150429-08:55:57.268(2)?     at packages/ddp/livedata_server.js:546:1
```
